In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('odb.csv')
df.head(5) # first 5 records display

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
1,1,V Kohli (INDIA),2008-2021,254,245,39,12169,183,59.07,13061,93.17,43,62,13,1140,125
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,1231,162
3,3,RG Sharma (INDIA),2007-2021,227,220,32,9205,264,48.96,10354,88.90,29,43,13,832,244
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34,1500,270

In [ ]:
df.tail(5)
# last 5 records display

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
114,114,SK Raina (INDIA),2005-2018,226,194,35,5615,116*,35.31,6005,93.50,5,36,14,476,120
115,115,H Masakadza (ZIM),2001-2019,209,208,4,5658,178*,27.73,7728,73.21,5,34,15,585,86
116,116,RB Richardson (WI),1983-1996,224,217,30,6248,122,33.41,9801,63.74,5,44,8,541+,54+
117,117,BB McCullum (NZ),2002-2016,260,228,28,6083,166,30.41,6312,96.37,5,32,20,577,200
118,118,Saleem Malik (PAK),1982-1999,283,256,38,7170,102,32.88,9383,76.41,5,47,19,514+,34+

In [ ]:
df.info() #  Shows data types, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  119 non-null    int64
 1   Player      119 non-null    object
 2   Span        119 non-null    object
 3   Mat         119 non-null    int64
 4   Inns        119 non-null    int64
 5   NO          119 non-null    int64
 6   Runs        119 non-null    int64
 7   HS          119 non-null    object
 8   Ave         119 non-null    float64
 9   BF          119 non-null    int64
 10  SR          119 non-null    float64
 11  100         119 non-null    int64
 12  50          119 non-null    int64
 13  0           119 non-null    int64
 14  4s          119 non-null    object
 15  6s          119 non-null    object
dtypes: float64(2), int64(9), object(5)
memory usage: 15.0+ KB

In [ ]:
df.describe() # Generates summary statistics (mean, median, min, max) for numerical columns.

,Unnamed: 0,Mat,Inns,NO,Runs,Ave,BF,SR,100,50,0
count,119.000000,119.000000,119.000000,119.00000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000
mean,59.000000,194.672269,184.411765,21.10084,6306.890756,39.347983,7897.941176,81.262605,11.487395,37.008403,10.915966
std,34.496377,94.879684,89.115276,15.81803,3091.187863,7.013547,3894.847910,11.402961,7.577694,20.005294,6.319971
min,0.000000,33.000000,32.000000,1.00000,1447.000000,23.570000,1360.000000,55.930000,5.000000,4.000000,1.000000
25%,29.500000,124.500000,120.000000,8.00000,3928.500000,34.910000,5086.000000,73.455000,6.000000,20.500000,6.000000
50%,59.000000,190.000000,181.000000,16.00000,5964.000000,38.000000,7678.000000,79.980000,9.000000,36.000000,10.000000
75%,88.500000,247.500000,236.500000,33.00000,8079.000000,42.450000,9780.500000,88.405000,14.500000,47.500000,15.000000
max,118.000000,463.000000,452.000000,84.00000,18426.000000,67.000000,21368.000000,118.660000,49.000000,96.000000,34.000000

In [ ]:
df.shape # Show how many rows and columns

(119, 16)

In [ ]:
df['Player'] # show columns

0         SR Tendulkar (INDIA)
1              V Kohli (INDIA)
2         RT Ponting (AUS/ICC)
3            RG Sharma (INDIA)
4      ST Jayasuriya (Asia/SL)
                ...
114           SK Raina (INDIA)
115          H Masakadza (ZIM)
116         RB Richardson (WI)
117           BB McCullum (NZ)
118         Saleem Malik (PAK)
Name: Player, Length: 119, dtype: object

In [ ]:
df.iloc[24] # Selects the first row of the DataFrame

Unnamed: 0                 24
Player        MJ Guptill (NZ)
Span                2009-2021
Mat                       186
Inns                      183
NO                         19
Runs                     6927
HS                       237*
Ave                     42.23
BF                       7896
SR                      87.72
100                        16
50                         37
0                          15
4s                        702
6s                        181
Name: 24, dtype: object

In [ ]:
df.query('Runs > 10000') # Example: select rows where the 'Runs' column is greater than 10000

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
1,1,V Kohli (INDIA),2008-2021,254,245,39,12169,183,59.07,13061,93.17,43,62,13,1140,125
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,1231,162
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34,1500,270
7,7,CH Gayle (ICC/WI),1999-2019,301,294,17,10480,215,37.83,12019,87.19,25,54,25,1128,331
8,8,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15,1385,88
9,9,SC Ganguly (Asia/INDIA),1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72,16,1122,190
10,10,TM Dilshan (SL),1999-2016,330,303,41,10290,161*,39.27,11933,86.23,22,47,11,1111,55
14,14,BC Lara (ICC/WI),1990-2007,299,289,32,10405,169,40.48,13086,79.51,19,63,16,1042,133
15,15,DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28,1119,76
21,21,JH Kallis (Afr/ICC/SA),1996-2014,328,314,53,11579,139,44.36,15885,72.89,17,86,17,911,137
39,39,R Dravid (Asia/ICC/INDIA),1996-2011,344,318,40,10889,153,39.16,15285,71.23,12,83,13,950,42
56,56,MS Dhoni (Asia/INDIA),2004-2019,350,297,84,10773,183*,50.57,12303,87.56,10,73,10,826,229
57,57,Inzamam-ul-Haq (Asia/PAK),1991-2007,378,350,53,11739,137*,39.52,15812,74.24,10,83,20,971,144

In [ ]:
df.dropna() # Drops rows or columns containing missing values

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
1,1,V Kohli (INDIA),2008-2021,254,245,39,12169,183,59.07,13061,93.17,43,62,13,1140,125
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,1231,162
3,3,RG Sharma (INDIA),2007-2021,227,220,32,9205,264,48.96,10354,88.90,29,43,13,832,244
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34,1500,270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,114,SK Raina (INDIA),2005-2018,226,194,35,5615,116*,35.31,6005,93.50,5,36,14,476,120
115,115,H Masakadza (ZIM),2001-2019,209,208,4,5658,178*,27.73,7728,73.21,5,34,15,585,86
116,116,RB Richardson (WI),1983-1996,224,217,30,6248,122,33.41,9801,63.74,5,44,8,541+,54+
117,117,BB McCullum (NZ),2002-2016,260,228,28,6083,166,30.41,6312,96.37,5,32,20,577,200
118,118,Saleem Malik (PAK),1982-1999,283,256,38,7170,102,32.88,9383,76.41,5,47,19,514+,34+

In [ ]:
df.drop_duplicates() # Removes identical rows from the dataset

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
1,1,V Kohli (INDIA),2008-2021,254,245,39,12169,183,59.07,13061,93.17,43,62,13,1140,125
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,1231,162
3,3,RG Sharma (INDIA),2007-2021,227,220,32,9205,264,48.96,10354,88.90,29,43,13,832,244
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34,1500,270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,114,SK Raina (INDIA),2005-2018,226,194,35,5615,116*,35.31,6005,93.50,5,36,14,476,120
115,115,H Masakadza (ZIM),2001-2019,209,208,4,5658,178*,27.73,7728,73.21,5,34,15,585,86
116,116,RB Richardson (WI),1983-1996,224,217,30,6248,122,33.41,9801,63.74,5,44,8,541+,54+
117,117,BB McCullum (NZ),2002-2016,260,228,28,6083,166,30.41,6312,96.37,5,32,20,577,200
118,118,Saleem Malik (PAK),1982-1999,283,256,38,7170,102,32.88,9383,76.41,5,47,19,514+,34+

In [ ]:
df1 = df.drop(columns=['Span']) # delete column
df1.head()

,Unnamed: 0,Player,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
1,1,V Kohli (INDIA),254,245,39,12169,183,59.07,13061,93.17,43,62,13,1140,125
2,2,RT Ponting (AUS/ICC),375,365,39,13704,164,42.03,17046,80.39,30,82,20,1231,162
3,3,RG Sharma (INDIA),227,220,32,9205,264,48.96,10354,88.90,29,43,13,832,244
4,4,ST Jayasuriya (Asia/SL),445,433,18,13430,189,32.36,14725,91.20,28,68,34,1500,270

In [ ]:
df.sort_values(by='Runs', ascending=False) # Rearranges dataset rows based on column value

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
8,8,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15,1385,88
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,1231,162
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34,1500,270
15,15,DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28,1119,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,CS MacLeod (SCOT),2008-2021,72,70,6,2290,175,35.78,2863,79.98,8,8,9,234,25
73,73,Imam-ul-Haq (PAK),2017-2021,46,46,5,2023,151,49.34,2519,80.30,7,10,3,161,16
97,97,RN ten Doeschate (NED),2006-2011,33,32,9,1541,119,67.00,1757,87.70,5,9,1,130,29
98,98,KL Rahul (INDIA),2016-2021,38,37,6,1509,112,48.67,1690,89.28,5,9,2,114,36
99,99,SO Hetmyer (WI),2017-2021,47,44,3,1447,139,35.29,1360,106.39,5,4,2,111,52